version: "3.7"
services:
  database:
    build: ./Database
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "track4go"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - trackgo_net
  backend:
    build: ./Track4GoBackend
    container_name: api
    image: mcr.microsoft.com/dotnet/sdk:3.1-alpine
    ports:
      - "15001:5001"
    volumes:
      - apidata:/usr/src/Track4GoBackend
    networks:
      - trackgo_net
    depends_on:
        - database
  frontend:
      build: ./track4go-frontend
      container_name: react
      image: node:16-alpine3.13
      ports:
          - 3000:3000
      volumes: 
          - frontendata:/usr/src/react
      networks:
        - trackgo_net
      depends_on:
          - backend
volumes:
  pgdata: {}
  apidata: {}
  frontendata: {}
networks:
  trackgo_net:
    external: true
    name: trackgo_net
    driver: bridge
